fileName = 'fit_pinn_results_positive_fastgate.mat';

% Show every variable stored in the file
whos('-file', fileName)

% Load the results
results = load(fileName);

% Display the saved field names
disp(fieldnames(results))
fitIdx = double(results.fit_idx(:));

parameterTable = table( ...
    fitIdx, ...
    string(results.par_names(fitIdx))', ...
    double(results.base_pars(fitIdx)), ...
    double(results.new_pars(fitIdx)), ...
    'VariableNames', ...
    {'Index', 'Parameter', 'StartingValue', 'FittedValue'});

disp(parameterTable)

initIdx = double(results.init_idx(:));

initialConditionTable = table( ...
    initIdx, ...
    string(results.init_names(:)), ...
    double(results.base_Init(initIdx)), ...
    double(results.new_Init(initIdx)), ...
    'VariableNames', ...
    {'Index', 'InitialCondition', 'StartingValue', 'FittedValue'});

disp(initialConditionTable)